name: Build Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**' # 监听 frontend 文件夹下的所有变化
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.0

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Vue project
        run: npm run build
        working-directory: ./frontend

      - name: Upload Artifact # 上传前端打包文件
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./frontend/dist
